language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - pip install -U cpplint
    - platformio update

script:
    - platformio run
    - cpplint --filter=-build/include_subdir,-runtime/int --exclude=colormap.h --recursive src/* include/*
